---
galaxy_info:
  author: Prakhar Srivastava
  description: Deploy single or multiple AAP instances on OpenShift
  company: Red Hat
  license: GPL-2.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - ansible
    - automation
    - aap
    - openshift

dependencies: []

collections:
  - kubernetes.core
