---
# Deploy multiple AAP instances for multi-user scenarios
# Integrates with RHSSO/htpasswd user provisioning

- name: Build list of instance namespaces matching user accounts
  ansible.builtin.set_fact:
    _aap_instance_namespaces: "{{ _aap_instance_namespaces | default([]) + [{'name': aap_instance_user_prefix ~ (item | string) ~ '-' ~ aap_instance_name, 'namespace': aap_instance_user_prefix ~ (item | string) ~ '-' ~ aap_instance_namespace, 'user': aap_instance_user_prefix ~ (item | string)}] }}"
  loop: "{{ range(1, aap_instance_num_users | int + 1) | list }}"

- name: Display multi-user deployment plan
  ansible.builtin.debug:
    msg:
      - "Deploying {{ aap_instance_num_users }} AAP instances for multi-user environment"
      - "Matching users: {{ _aap_instance_namespaces | map(attribute='user') | list }}"
      - "Instances: {{ _aap_instance_namespaces | map(attribute='name') | list }}"
      - "Namespaces: {{ _aap_instance_namespaces | map(attribute='namespace') | list }}"

- name: Create namespaces for each user instance
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item.namespace }}"
        labels:
          app: ansible-automation-platform
          instance: "{{ item.name }}"
          deployment-mode: multi-user
  loop: "{{ _aap_instance_namespaces }}"

- name: Create OperatorGroup for each namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: "{{ item.name }}-operatorgroup"
        namespace: "{{ item.namespace }}"
      spec:
        targetNamespaces:
          - "{{ item.namespace }}"
  loop: "{{ _aap_instance_namespaces }}"

- name: Create AAP operator subscription for each namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ aap_instance_operator_name }}"
        namespace: "{{ item.namespace }}"
      spec:
        channel: "{{ aap_instance_operator_channel }}"
        installPlanApproval: "{{ 'Automatic' if aap_instance_automatic_install_plan_approval else 'Manual' }}"
        name: "{{ aap_instance_operator_name }}"
        source: "{{ aap_instance_operator_catalog if not aap_instance_use_catalog_snapshot else aap_instance_catalogsource_name }}"
        sourceNamespace: "{{ 'openshift-marketplace' if not aap_instance_use_catalog_snapshot else item.namespace }}"
        startingCSV: "{{ aap_instance_starting_csv if aap_instance_starting_csv | length > 0 else omit }}"
  loop: "{{ _aap_instance_namespaces }}"

- name: Wait for operators to be ready
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: "{{ item.namespace }}"
  register: r_csv_multi
  until:
    - r_csv_multi.resources | length > 0
    - r_csv_multi.resources[0].status.phase is defined
    - r_csv_multi.resources[0].status.phase == "Succeeded"
  retries: 30
  delay: 30
  loop: "{{ _aap_instance_namespaces }}"

- name: Deploy AAP instance for each user
  ansible.builtin.include_tasks: deploy_instance.yml
  vars:
    _instance_name: "{{ item.name }}"
    _instance_namespace: "{{ item.namespace }}"
  loop: "{{ _aap_instance_namespaces }}"

- name: Print multi-user deployment summary
  ansible.builtin.debug:
    msg:
      - "Multi-user AAP deployment complete"
      - "Total instances deployed: {{ aap_instance_num_users }}"
      - "Users provisioned: {{ aap_instance_user_prefix }}1 through {{ aap_instance_user_prefix }}{{ aap_instance_num_users }}"
      - "AAP version: {{ aap_instance_version }}"
      - "Components per instance:"
      - "  - Controller: {{ aap_instance_enable_controller }}"
      - "  - EDA: {{ aap_instance_enable_eda }}"
      - "  - Hub: {{ aap_instance_enable_hub }}"
      - "  - Lightspeed: {{ aap_instance_enable_lightspeed }}"
