---
# Setup AAP operator and prerequisites

- name: Create namespace for AAP operator (single instance mode)
  when: not aap_instance_multi_user | bool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ aap_instance_namespace }}"
        labels:
          app: ansible-automation-platform
          instance: "{{ aap_instance_name }}"

- name: Extend OCP bearer token lifecycle for AAP credentials
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec:
        tokenConfig:
          accessTokenMaxAgeSeconds: "{{ aap_instance_ocp_token_lifecycle }}"

- name: Setup catalog snapshot (if enabled)
  when: aap_instance_use_catalog_snapshot | bool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        name: "{{ aap_instance_catalogsource_name }}"
        namespace: "{{ aap_instance_namespace }}"
      spec:
        sourceType: grpc
        image: "{{ aap_instance_catalog_snapshot_image }}:{{ aap_instance_catalog_snapshot_image_tag }}"
        displayName: Red Hat Operators Snapshot
        publisher: Red Hat

- name: Create OperatorGroup for AAP (single instance)
  when: not aap_instance_multi_user | bool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: "{{ aap_instance_name }}-operatorgroup"
        namespace: "{{ aap_instance_namespace }}"
      spec:
        targetNamespaces:
          - "{{ aap_instance_namespace }}"

- name: Create AAP operator subscription (single instance)
  when: not aap_instance_multi_user | bool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ aap_instance_operator_name }}"
        namespace: "{{ aap_instance_namespace }}"
      spec:
        channel: "{{ aap_instance_operator_channel }}"
        installPlanApproval: "{{ 'Automatic' if aap_instance_automatic_install_plan_approval else 'Manual' }}"
        name: "{{ aap_instance_operator_name }}"
        source: "{{ aap_instance_operator_catalog if not aap_instance_use_catalog_snapshot else aap_instance_catalogsource_name }}"
        sourceNamespace: "{{ 'openshift-marketplace' if not aap_instance_use_catalog_snapshot else aap_instance_namespace }}"
        startingCSV: "{{ aap_instance_starting_csv if aap_instance_starting_csv | length > 0 else omit }}"

- name: Wait for AAP operator to be ready
  when: not aap_instance_multi_user | bool
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: "{{ aap_instance_namespace }}"
  register: r_csv
  until:
    - r_csv.resources | length > 0
    - r_csv.resources[0].status.phase is defined
    - r_csv.resources[0].status.phase == "Succeeded"
  retries: 30
  delay: 30
