---
# Validate input parameters

- name: Validate AAP version
  ansible.builtin.assert:
    that:
      - aap_instance_version in ['2.5', '2.6']
    fail_msg: "aap_instance_version must be either '2.5' or '2.6'"
    success_msg: "AAP version {{ aap_instance_version }} is valid"

- name: Validate at least one component is enabled
  ansible.builtin.assert:
    that:
      - aap_instance_enable_controller or
        aap_instance_enable_eda or
        aap_instance_enable_hub or
        aap_instance_enable_lightspeed
    fail_msg: "At least one AAP component must be enabled"
    success_msg: "Component validation passed"

- name: Validate multi-user configuration
  when: aap_instance_multi_user | bool
  ansible.builtin.assert:
    that:
      - aap_instance_num_users | int > 1
      - aap_instance_num_users | int <= 50
    fail_msg: "num_users must be between 2 and 50 for multi-user mode"
    success_msg: "Multi-user configuration is valid ({{ aap_instance_num_users }} users)"

- name: Display deployment configuration
  ansible.builtin.debug:
    msg:
      - "AAP Deployment Configuration:"
      - "  Version: {{ aap_instance_version }}"
      - "  Multi-user mode: {{ aap_instance_multi_user }}"
      - "  Number of users: {{ aap_instance_num_users }}"
      - "  User prefix: {{ aap_instance_user_prefix }}"
      - "  Components enabled:"
      - "    - Controller: {{ aap_instance_enable_controller }}"
      - "    - EDA: {{ aap_instance_enable_eda }}"
      - "    - Hub: {{ aap_instance_enable_hub }}"
      - "    - Lightspeed: {{ aap_instance_enable_lightspeed }}"
