#SPDX-License-Identifier: MIT-0
---
namespace: rhpds
name: aap_self_service_portal
version: 1.0.0
readme: README.md
authors:
  - Hicham Mourad <hmourad@redhat.com>
  - Prakhar Srivastava <psrivast@redhat.com>
description: Ansible collection for deploying AAP multi-instance and Self-Service Portal on OpenShift
license:
  - MIT
tags:
  - ansible
  - aap
  - automation
  - openshift
  - self-service
  - rhdp
dependencies:
  kubernetes.core: ">=2.3.0"
  redhat.openshift: ">=2.0.0"
repository: https://github.com/rhpds/rhpds.aap_self_service_portal
documentation: https://github.com/rhpds/rhpds.aap_self_service_portal
homepage: https://github.com/rhpds/rhpds.aap_self_service_portal
issues: https://github.com/rhpds/rhpds.aap_self_service_portal/issues
