---
# Ansible collection requirements for rhpds.aap_self_service_portal
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: kubernetes.core
    version: ">=2.3.0"
